language: android
jdk: oraclejdk7
env:
  matrix:
  - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
android:
  components:
  - build-tools-19.1
before_script:
- cp keystore.properties.example keystore.properties
- cp local.properties.example local.properties
script: "./gradlew clean assembleDebug"
deploy:
  provider: releases
  api_key:
    secure: Y5kfBQn9BMiDmgDjl0ypKVZfVuVvUTtwFVIZ6GoBnbl0q+iUDHLhBngmbUOymcLE9dA15kZCZgYN+zW/eYl0Y75n98KWeYyYzVtLapiI9CM3+yLW3N/rzREWdJ3NLI57G2yeKtOhOhwtPsxizGhOJ2HwPa+SNGinf03s9NgtS7s=
  file: ${TRAVIS_BUILD_DIR}/lastcall/build/outputs/apk/lastcall-debug.apk
  on:
    repo: dinosaurwithakatana/lastcaller
    branch: master
    tags: true
    all_branches: true
